"""add role and withdrawal status

Revision ID: 7496deaf062a
Revises: 048618aa365b
Create Date: 2026-07-05 11:57:44.394098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7496deaf062a'
down_revision: Union[str, Sequence[str], None] = '048618aa365b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=16), nullable=False, server_default='user'))
    op.add_column('withdrawal_requests', sa.Column('taken_by', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal_requests', 'taken_by')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
